// src/app/api/guru/guruCompiler.js

export function composeGuruResponse({
  mode,
  derech,
  topic,
  sources = [],
  sugyaTree = {},
  chakira = {},
  nafkaMinot = [],
  halachicFlow = {},
  additionalSections = {},
}) {
  let output = "";

  output += `# 📚 Mode: ${mode.toUpperCase()} | Derech: ${derech || "default"}\n\n`;
  output += `## ✨ Topic: ${topic || "N/A"}\n\n`;

  // Torah Sources
  if (sources.length) {
    output += `## 📘 Torah Sources:\n\n`;
    sources.forEach((src, idx) => {
      output += `**${idx + 1}.** ${src.title} (${src.type})\n`;
      if (src.hebrew) output += `- **Hebrew:** ${src.hebrew}\n`;
      if (src.english) output += `- **English:** ${src.english}\n`;
      if (src.notes) output += `- _Notes:_ ${src.notes}\n`;
      output += `\n`;
    });
  }

  // Sugya Tree
  if (sugyaTree?.nodes?.length) {
    output += `## 🌲 Sugya Tree:\n\n`;
    sugyaTree.nodes.forEach((node, i) => {
      output += `- ${i + 1}. **${node.label}** → ${node.description}\n`;
    });
    output += `\n`;
  }

  // Chakira
  if (chakira?.question) {
    output += `## 🧠 Brisker Chakira:\n\n`;
    output += `- **Chakira:** ${chakira.question}\n`;
    output += `- **Side A:** ${chakira.sideA}\n`;
    output += `- **Side B:** ${chakira.sideB}\n\n`;
  }

  // Nafka Minot
  if (nafkaMinot.length) {
    output += `## ⚖️ Nafka Minot:\n\n`;
    nafkaMinot.forEach((nm, idx) => {
      output += `**${idx + 1}. ${nm.label}**\n`;
      output += `- Scenario: ${nm.scenario}\n`;
      output += `- Halachic Difference: ${nm.halachic_difference}\n`;
      if (nm.relevant_sources?.length) {
        output += `- Sources: ${nm.relevant_sources.join(", ")}\n`;
      }
      output += `\n`;
    });
  }

  // Halachic Flow
  if (halachicFlow) {
    output += `## 📜 Halachic Flow:\n\n`;

    const { talmud = [], rishonim = [], shulchan_aruch = [], acharonim = [] } = halachicFlow;

    if (talmud.length) {
      output += `### 🟦 Talmud:\n`;
      talmud.forEach((t) => {
        output += `- ${t.source}: ${t.summary}\n`;
      });
      output += `\n`;
    }

    if (rishonim.length) {
      output += `### 🟩 Rishonim:\n`;
      rishonim.forEach((r) => {
        output += `- ${r.name} (${r.source}): ${r.view}\n`;
      });
      output += `\n`;
    }

    if (shulchan_aruch.length) {
      output += `### 🟥 Shulchan Aruch:\n`;
      shulchan_aruch.forEach((sa) => {
        output += `- Siman ${sa.seif}: ${sa.ruling}`;
        if (sa.aligned_rishonim?.length) {
          output += ` (Based on: ${sa.aligned_rishonim.join(", ")})`;
        }
        output += `\n`;
      });
      output += `\n`;
    }

    if (acharonim.length) {
      output += `### 🟪 Acharonim:\n`;
      acharonim.forEach((a) => {
        output += `- ${a.name}: ${a.view}\n`;
      });
      output += `\n`;
    }
  }

  // Additional Sections (e.g., Midrash, Liturgy)
  if (Object.keys(additionalSections).length) {
    output += `## 🔍 Additional Insights:\n\n`;
    Object.entries(additionalSections).forEach(([section, content]) => {
      output += `### ${section}:\n${content}\n\n`;
    });
  }

  // Final fallback
  return output || "❌ No content generated by agents.";
}


